// Constants for Students
export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";

export const STUDENT_REGISTER_REQUEST = "STUDENT_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "STUDENT_REGISTER_FAIL";

export const LOAD_STUDENT_REQUEST = "LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL = "LOAD_STUDENT_FAIL";

export const STUDENT_LOGOUT_REQUEST = "STUDENT_LOGOUT_REQUEST";
export const STUDENT_LOGOUT_SUCCESS = "STUDENT_LOGOUT_SUCCESS";
export const STUDENT_LOGOUT_FAIL = "STUDENT_LOGOUT_FAIL";

// Constants for Universities
export const UNIVERSITY_LOGIN_REQUEST = "UNIVERSITY_LOGIN_REQUEST";
export const UNIVERSITY_LOGIN_SUCCESS = "UNIVERSITY_LOGIN_SUCCESS";
export const UNIVERSITY_LOGIN_FAIL = "UNIVERSITY_LOGIN_FAIL";

export const UNIVERSITY_REGISTER_REQUEST = "UNIVERSITY_REGISTER_REQUEST";
export const UNIVERSITY_REGISTER_SUCCESS = "UNIVERSITY_REGISTER_SUCCESS";
export const UNIVERSITY_REGISTER_FAIL = "UNIVERSITY_REGISTER_FAIL";

export const LOAD_UNIVERSITY_REQUEST = "LOAD_UNIVERSITY_REQUEST";
export const LOAD_UNIVERSITY_SUCCESS = "LOAD_UNIVERSITY_SUCCESS";
export const LOAD_UNIVERSITY_FAIL = "LOAD_UNIVERSITY_FAIL";

export const UNIVERSITY_LOGOUT_REQUEST = " UNIVERSITY_LOGOUT_REQUEST";
export const UNIVERSITY_LOGOUT_SUCCESS = "UNIVERSITY_LOGOUT_SUCCESS";
export const UNIVERSITY_LOGOUT_FAIL = "UNIVERSITY_LOGOUT_FAIL";

// Constants for Employers
export const EMPLOYER_LOGIN_REQUEST = "EMPLOYER_LOGIN_REQUEST";
export const EMPLOYER_LOGIN_SUCCESS = "EMPLOYER_LOGIN_SUCCESS";
export const EMPLOYER_LOGIN_FAIL = "EMPLOYER_LOGIN_FAIL";

export const EMPLOYER_REGISTER_REQUEST = "EMPLOYER_REGISTER_REQUEST";
export const EMPLOYER_REGISTER_SUCCESS = "EMPLOYER_REGISTER_SUCCESS";
export const EMPLOYER_REGISTER_FAIL = "EMPLOYER_REGISTER_FAIL";

export const LOAD_EMPLOYER_REQUEST = "LOAD_EMPLOYER_REQUEST";
export const LOAD_EMPLOYER_SUCCESS = "LOAD_EMPLOYER_SUCCESS";
export const LOAD_EMPLOYER_FAIL = "LOAD_EMPLOYER_FAIL";

export const EMPLOYER_LOGOUT_REQUEST = " EMPLOYER_LOGOUT_REQUEST";
export const EMPLOYER_LOGOUT_SUCCESS = "EMPLOYER_LOGOUT_SUCCESS";
export const EMPLOYER_LOGOUT_FAIL = "EMPLOYER_LOGOUT_FAIL";

// Common Constants
export const CLEAR_ERRORS = "CLEAR_ERRORS";
